import Head from 'next/head'
import Link from 'next/link'
import Nav from '../Nav'
import Footer from '../Footer'
import { words } from '../wordsData'
import styles from '../styles/Home.module.css'
import utilStyles from '../styles/utils.module.css'
import React, { useState } from 'react';
import Scroll from '../components/ScrollToTop'

export default function Home () {
  const [input, setInput] = useState('')
  let inputs = input.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "").toString().toLowerCase()
  let result = true;
  let wordsData = words

  const handleChange = (e) => {
      e.preventDefault()
      setInput(e.target.value)
  }

  if (inputs.length > 0) {
      wordsData = wordsData.filter((i) => {
          return i.word.toLowerCase().match(inputs)
      })
  }

  return (
    <div className={ styles.container }>
      <Head>
        <title>Vietnamese Words</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className={`${ styles.main } ${ utilStyles.main }`}>
        <header className={ styles.header }>
        <h1 className={`${ styles.title }  ${ utilStyles.h1L }`}>
          <ruby>詞語越南<rt>Từ Ngữ Việt Nam</rt></ruby><br></br>Vietnamese Words 
        </h1>
        
        <p className={ styles.description }>
          Vietnamese abbreviations / slangs / social media &amp; messaging language 
        </p>

          <input 
          type="text" 
          className={`${ styles.input } ${ utilStyles.borderRadius }`} 
          aria-label="search bar"
          placeholder="search word"
          value={ inputs }
          onChange={ handleChange }
          ></input>
        </header>

        <div className={ styles.grid }>
        {wordsData.reverse().map((word, index) => (
          <>
          <Link key={ index } href={`/word/${ word.id }`}>
            <a className={`${ utilStyles.card } ${ styles.smallCard } ${ utilStyles.borderRadius }`}>
              <h2>{ word.word }</h2>
              <p>{ word.word } is { word.meaning }</p>
              <p className={`${ utilStyles.overflow } ${styles.eng}`}>
                Eng: { word.english }
              </p>
            </a>
          </Link>
          </>
        ))}
        </div>
      </main>
      <Footer />
    </div>
  )
}
