import Head from 'next/head'
import Link from 'next/link'
import Nav from '../Nav'
import Footer from '../Footer'
import utilStyles from '../styles/utils.module.css'

export default function Home() {
    return (
        <>
        <Head>
            <title>Submit Word</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        <main className={`${ utilStyles.paddingTop }`}>
            <h1>Submit Word</h1>
        </main>
        <Footer />
        </>
    )
}
